import type { JsonValue } from '#protocol';
import type { Behaviour, BehaviourDefinition, BehaviourStatus, ReflexContext, ValidationResult } from '../../core/reflex.ts';
interface FletchParams { readonly product: number; readonly amount: number; readonly timeoutTicks?: number; }
const obj = (value: unknown): value is Record<string, unknown> => typeof value === 'object' && value !== null && !Array.isArray(value);
const positive = (value: unknown): value is number => Number.isSafeInteger(value) && (value as number) > 0;
function validate(value: unknown): ValidationResult { const errors: { path: string; message: string }[] = []; if (!obj(value)) return { ok: false, errors: [{ path: 'params', message: 'must be an object' }] }; if (!positive(value.product)) errors.push({ path: 'product', message: 'must be a positive item id' }); if (!positive(value.amount)) errors.push({ path: 'amount', message: 'must be a positive operation count' }); if (value.timeoutTicks !== undefined && !positive(value.timeoutTicks)) errors.push({ path: 'timeoutTicks', message: 'must be a positive integer' }); return { ok: errors.length === 0, errors }; }
class FletchLoopBehaviour implements Behaviour {
  readonly id = 'fletch-loop'; readonly params: Readonly<Record<string, JsonValue>>; private readonly config: FletchParams; private startedTick?: number; private active = false; private produced = 0;
  constructor(params: FletchParams) { this.config = params; this.params = params as unknown as Readonly<Record<string, JsonValue>>; }
  private async drive(ctx: ReflexContext, initial: boolean): Promise<BehaviourStatus> { const snapshot = ctx.view.snapshot(); this.startedTick ??= ctx.tick; if (ctx.tick - this.startedTick >= (this.config.timeoutTicks ?? 200)) return { state: 'failed', reason: 'timeout', retryable: true }; for (const event of ctx.pulseEvents) { if (event.type === 'fletched' && event.data.entity === snapshot.self.entity && event.data.product === this.config.product) this.produced += event.data.amount; if (event.type === 'fletching-stopped' && event.data.entity === snapshot.self.entity) { this.active = false; return event.data.reason === 'completed' ? { state: 'done', summary: `fletched ${this.produced} of item#${this.config.product}` } : { state: 'failed', reason: event.data.reason, retryable: false }; } } if (initial && !this.active) { const outcome = await ctx.act({ type: 'fletch', data: { product: this.config.product, amount: this.config.amount } }); if (!outcome.ok) return { state: 'failed', reason: outcome.code ?? outcome.message ?? 'fletch rejected', retryable: false }; this.active = true; } return { state: 'running', note: `${this.produced} output made` }; }
  start(ctx: ReflexContext): Promise<BehaviourStatus> { return this.drive(ctx, true); } step(ctx: ReflexContext): Promise<BehaviourStatus> { return this.drive(ctx, false); }
  async stop(ctx: ReflexContext, why: 'done' | 'failed' | 'replaced' | 'cancelled'): Promise<void> { if (this.active && (why === 'replaced' || why === 'cancelled')) await ctx.act({ type: 'stop-fletch', data: {} }); }
  describe(): string { return `fletch-loop item#${this.config.product} ${this.produced} output`.slice(0, 80); }
}
export const FLETCH_LOOP: BehaviourDefinition = { id: 'fletch-loop', description: 'Make a bounded number of fletching recipe operations and stop on missing inputs.', paramsSchema: { type: 'object', required: ['product', 'amount'], additionalProperties: false, properties: { product: { type: 'integer', minimum: 1 }, amount: { type: 'integer', minimum: 1 }, timeoutTicks: { type: 'integer', minimum: 1, default: 200 } } }, validate, create: (params) => new FletchLoopBehaviour(params as unknown as FletchParams) };

