import type { JsonValue } from '#protocol';
import type { Behaviour, BehaviourDefinition, BehaviourStatus, ReflexContext, ValidationResult } from '../../core/reflex.ts';
type HerbloreParams = { readonly action: 'clean'; readonly item: number; readonly amount?: number; readonly timeoutTicks?: number } | { readonly action: 'make'; readonly product: number; readonly amount: number; readonly timeoutTicks?: number };
const obj = (value: unknown): value is Record<string, unknown> => typeof value === 'object' && value !== null && !Array.isArray(value); const positive = (value: unknown): value is number => Number.isSafeInteger(value) && (value as number) > 0;
function validate(value: unknown): ValidationResult { const errors: { path: string; message: string }[] = []; if (!obj(value)) return { ok: false, errors: [{ path: 'params', message: 'must be an object' }] }; if (value.action !== 'clean' && value.action !== 'make') errors.push({ path: 'action', message: 'must be clean or make' }); if (value.action === 'clean' && !positive(value.item)) errors.push({ path: 'item', message: 'must be a positive grimy-herb item id' }); if (value.action === 'make' && !positive(value.product)) errors.push({ path: 'product', message: 'must be a positive recipe product id' }); if (value.action === 'make' && !positive(value.amount)) errors.push({ path: 'amount', message: 'must be a positive operation count' }); if (value.action === 'clean' && value.amount !== undefined && !positive(value.amount)) errors.push({ path: 'amount', message: 'must be a positive operation count' }); if (value.timeoutTicks !== undefined && !positive(value.timeoutTicks)) errors.push({ path: 'timeoutTicks', message: 'must be a positive integer' }); return { ok: errors.length === 0, errors }; }
class HerbloreLoopBehaviour implements Behaviour {
  readonly id = 'herblore-loop'; readonly params: Readonly<Record<string, JsonValue>>; private readonly config: HerbloreParams; private startedTick?: number; private active = false; private made = 0;
  constructor(params: HerbloreParams) { this.config = params; this.params = params as unknown as Readonly<Record<string, JsonValue>>; }
  private async drive(ctx: ReflexContext, initial: boolean): Promise<BehaviourStatus> { const snapshot = ctx.view.snapshot(); this.startedTick ??= ctx.tick; if (ctx.tick - this.startedTick >= (this.config.timeoutTicks ?? 200)) return { state: 'failed', reason: 'timeout', retryable: true }; for (const event of ctx.pulseEvents) { if (this.config.action === 'clean' && event.type === 'herb-cleaned' && event.data.entity === snapshot.self.entity && event.data.herb === this.config.item) this.made++; if (this.config.action === 'make' && event.type === 'potion-made' && event.data.entity === snapshot.self.entity && event.data.product === this.config.product) this.made++; if (event.type === 'herblore-stopped' && event.data.entity === snapshot.self.entity) { this.active = false; return event.data.reason === 'completed' ? { state: 'done', summary: `${this.config.action === 'clean' ? 'cleaned' : 'made'} ${this.made}` } : { state: 'failed', reason: event.data.reason, retryable: false }; } } if (initial && !this.active) { const data = this.config.action === 'clean' ? { item: this.config.item, ...(this.config.amount === undefined ? {} : { amount: this.config.amount }) } : { product: this.config.product, amount: this.config.amount }; const outcome = await ctx.act({ type: this.config.action === 'clean' ? 'clean-herb' : 'make-potion', data }); if (!outcome.ok) return { state: 'failed', reason: outcome.code ?? outcome.message ?? 'herblore rejected', retryable: false }; this.active = true; } return { state: 'running', note: `${this.made} completed` }; }
  start(ctx: ReflexContext): Promise<BehaviourStatus> { return this.drive(ctx, true); } step(ctx: ReflexContext): Promise<BehaviourStatus> { return this.drive(ctx, false); }
  async stop(ctx: ReflexContext, why: 'done' | 'failed' | 'replaced' | 'cancelled'): Promise<void> { if (this.active && (why === 'replaced' || why === 'cancelled')) await ctx.act({ type: 'stop-herblore', data: {} }); }
  describe(): string { return `herblore-loop ${this.config.action} ${this.made} completed`.slice(0, 80); }
}
export const HERBLORE_LOOP: BehaviourDefinition = { id: 'herblore-loop', description: 'Clean all of one grimy herb stack or make a bounded number of herblore products.', paramsSchema: { oneOf: [{ type: 'object', required: ['action', 'item'], additionalProperties: false, properties: { action: { const: 'clean' }, item: { type: 'integer', minimum: 1 }, amount: { type: 'integer', minimum: 1 }, timeoutTicks: { type: 'integer', minimum: 1, default: 200 } } }, { type: 'object', required: ['action', 'product', 'amount'], additionalProperties: false, properties: { action: { const: 'make' }, product: { type: 'integer', minimum: 1 }, amount: { type: 'integer', minimum: 1 }, timeoutTicks: { type: 'integer', minimum: 1, default: 200 } } }] }, validate, create: (params) => new HerbloreLoopBehaviour(params as unknown as HerbloreParams) };
